### ISSUE TITLE
As a software team lead, I would like to submit my source code then receive a UML diagram and helpful commenting.

### ISSUE THREAD

**Issue by xaviergaray** [xaviergaray/OnboardingDocumentGenerator#1]
# Todo:
- [ ] Read and parse source code
- [ ] Generate UML Diagram
- [ ] Suggest comments to be placed in source code
- [ ] Make this a webapp that users can create an account for and submit payment information
